//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication16.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Seminari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seminari()
        {
            this.Predbiljezbe = new HashSet<Predbiljezbe>();
        }

        
        public int IdSeminar { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Maksimalno 50 znakova!")]
        [Display(Name = "Naziv tecaja")]
        public string Naziv { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "Maksimalno 100 znakova!")]
        public string Opis { get; set; }

        [Required]
        [StringLength(10, ErrorMessage = "Maksimalno 10 znakova!")]
        [Display(Name = "Datum pocetka")]
        [DataType(DataType.Date)]
        public string Datum { get; set; }

        public bool Popunjen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predbiljezbe> Predbiljezbe { get; set; }
    }
}
